// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YazilimGerceklemeMVC.Data;

#nullable disable

namespace YazilimGerceklemeMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221127152948_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YazilimGerceklemeTest.Models.Arac", b =>
                {
                    b.Property<int>("AracId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AracId"));

                    b.Property<string>("AracMarka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Motor")
                        .HasColumnType("real");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("AracId");

                    b.ToTable("Araclar");
                });
#pragma warning restore 612, 618
        }
    }
}
